name: Maven Auto Build

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: x64
      
    - name: Download Stable Spigot Buildtool
      run: |
        mkdir ./spigot
        cd ./spigot
        curl "https://hub.spigotmc.org/jenkins/job/BuildTools/lastStableBuild/artifact/target/BuildTools.jar" -o BuildTools.jar
      
    - name: Building Spigot
      run: |
       cd ./spigot
        java -jar BuildTools.jar --rev 1.12.2

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
    - name: Publish JAR
      run: ./mvnw -B release:prepare release:perform --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
