
name: Maven Auto Build

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 8                   



    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
    - name: Publish JAR
      run: ./mvnw -B release:prepare release:perform --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
